### ISSUE TITLE
Not able to import CITRUS clusters

### ISSUE THREAD

**Issue by vivek-verma202** [tchitchek-lab/CytoCompare#1]
> imported.citrus <- import.CITRUS('./citrusClustering.rData')
Importing ./citrusClustering.rData
Computation of marker means, standard deviations and densities...

The issue did not improve even when:

1) group number was specified in the argument: cluster.selection
2) .rData file was generated using Cytobank and not citrus rpackage.

r version: 3.5.0
Cytocompare: from Github, last week

Please help!
Thanks!
Vivek

**Comment by SamGG** [comment]
Hi,
I have just done a trial using example1 of the citrus package, and I didn't get any error. What's the error on your side?
Best

**Comment by SamGG** [comment]
Having looked at the code, I think the import function is not correct in the case of citrus. Clusters from citrus are not mutually exclusive but rather imbricated. This means that the events are repeated many times. Nicolas will fix this I guess.
Best.

**Comment by vivek-verma202** [comment]
Thanks alot Sam! Could you please let us know by when would the issue be fixed?

**Comment by vivek-verma202** [comment]
Hi Sam!

I just wanted to follow-up on the issue of using Citrus clusters with Cytocompare

**Comment by SamGG** [comment]
Hi. Nicolas is the maintainer of this package, I am just keeping an eye on this interesting work.
Best.

**Comment by vivek-verma202** [comment]
Thanks Sam!

**Comment by nicolas-tchitchek** [comment]
Dear Vivek,

Thank you again for your interest in CytoCompare and sorry for not having be more fast to process your query.

Indeed, it seems that a bug was present in CytoCompare in the import procedure from Citrus results. In fact, the bug is not related to the fact that Citrus produces overlapping cell clusters but rather to the fact that Citrus results have marker columns that should not be proceed. Some channels (especially the “time” channel) must be excluded when importing Citrus results (using the exclude parameter). We have now defined a set of channels to exclude when importing Citrus results. Sorry for this inconvenience.

Thank you and best regards,

Nicolas
